### ISSUE TITLE
fix: Non stop pending of run command document

### ISSUE THREAD

**Issue by JustinDPerkins** [trendmicro/cloudone-community#41]
# https://github.com/trendmicro/cloudone-community/tree/main/Workload-Security/Deployment/aws-python-agent-deploy-automation-using-lambda

## Describe the bug
Run Command document never leaves pending state. Instances are being tagged correctly but no agent is deployed.
No outputs were generated in the session.

## To reproduce
Just deploy it and it should replicate itself. Found during WS immersion day.

**Comment by felipecosta09** [comment]
So I've tested with @fernandostc and it looks like if you're having issues it might be intermittent or even something in the account, could you double-check?

**Comment by JustinDPerkins** [comment]
Yeah, it is working again. Odd, I was not the only one having this issue. Maybe it was AWS issue.
